{
    user(login:"${name}") {
        avatarUrl
        followers(first:${followersLimit}) {
            nodes {
                login
            }
        }
        following(first:${followingLimit}) {
            nodes {
                login
            }
        }
    }
}