{
    user(login:"${name}") {
        avatarUrl
        followers(first:${limit}) {
            nodes {
                login
            }
        }
        following(first:${limit}) {
            nodes {
                login
            }
        }
    }
}